### ISSUE TITLE
refactor: redesign agent configuration to support multiple session types

### ISSUE THREAD

**Issue by choplin** [choplin/amux#148]
## Overview

Following the session interface refactoring in #145, we need to redesign the agent configuration structure to support multiple session types cleanly.

## Current State

The current agent configuration is implicitly designed for tmux sessions:
- No explicit session type field
- Tmux-specific fields mixed with common fields
- Hard to extend for new session types

### 1. Make session type explicit and required

```yaml
agents:
  claude-tmux:
    name: Claude (Terminal)
    type: tmux  # Required field
    common:
      description: "Claude AI agent for terminal-based development"
      environment:
        ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      workingDir: "."
    tmux:  # tmux-specific settings
      command: "claude"
      shell: "/bin/bash"
      windowName: "claude-session"
```

### 2. New type definitions

```go
type Agent struct {
    Name        string            `yaml:"name"`
    Type        session.Type      `yaml:"type"`  // Required
    Common      CommonConfig      `yaml:"common"`
    
    // Type-specific configurations
    Tmux        *TmuxConfig       `yaml:"tmux,omitempty"`
    // Future: ClaudeCode, API, LSP, etc.
}
```

## Implementation Plan

1. Update config types to support new structure
2. Update config validation to require type field
3. Update session creation to use type-specific configs
4. Update default config and documentation
5. Add tests for new configuration structure

## Future Extensions

- `claude-code`: One-shot execution of Claude Code CLI
- `api`: Direct API-based sessions
- `lsp`: Language Server Protocol sessions

This design will make it easy to add new session types while keeping configurations clean and type-safe.
