### ISSUE TITLE
feat: add project-specific configuration options

### ISSUE THREAD

**Issue by choplin** [choplin/amux#160]
## Background

Currently, ProjectConfig exists but is empty after removing unused fields (#157). We should either remove it completely or add meaningful project-specific settings.

### 1. Workspace Management
```yaml
project:
  workspace:
    defaultBranch: develop  # Use branch other than main
    namePattern: "{type}-{issue}-{description}"  # e.g., feat-123-add-auth
    autoPrefix: true  # Automatically add prefixes
    maxAge: 30  # Auto-cleanup old workspaces (days)
```

### 2. Development Environment
```yaml
project:
  environment:  # Shared across all workspaces
    NODE_ENV: development
    API_BASE_URL: http://localhost:3000
  scripts:
    postCreate: "npm install && npm run setup"
    preRemove: "npm run cleanup"
```

### 3. Agent Behavior Control
```yaml
project:
  agents:
    defaultTimeout: 3600  # Session timeout in seconds
    autoRestart: true  # Auto-restart on crash
    resourceLimits:
      memory: "2GB"
      cpu: "50%"
```

### 4. Git Integration
```yaml
project:
  git:
    protectedBranches: ["main", "production"]  # Prevent direct work
    commitTemplate: ".gitmessage"  # Commit message template
    autoStash: true  # Auto-stash on workspace switch
```

### 5. Templates & Standardization
```yaml
project:
  templates:
    issue: "https://github.com/owner/repo/issues/{number}"
    pr: "feat: {description} (#{issue})"
  standards:
    testCommand: "npm test"
    lintCommand: "npm run lint"
    buildCommand: "npm run build"
```

## Decision

For now, we'll remove ProjectConfig completely following YAGNI principle. When we need project-specific settings, we can add them with proper design based on actual requirements.

## Related

- #157 - Removes unused fields from ProjectConfig

**Comment by choplin** [comment]
## #161との関連性について

#161（worktreeディレクトリ名のカスタマイズ）と本issueは密接に関連しており、統合的なアプローチで解決できそうです。

### 統合的な設計案

```yaml
# .amux/config.yaml
defaults:
  workspace:
    worktree_name_pattern: "{workspace_name}"  # #161の要件
    
  session:
    env:  # 本issueで特定されたニーズ
      EDITOR: "vim"
      NODE_ENV: "development"
```

### YAGNIの実践例として

これらの2つのissueは、YAGNIの良い実践例を示しています：

1. **当初**: ProjectConfigを削除（推測ベースの機能を避ける）
2. **実使用からの発見**:
   - グローバル環境変数の必要性（#159の議論）
   - worktreeディレクトリ名のカスタマイズ（#161）
3. **具体的ニーズに基づく設計**: 実際の問題から設定項目を追加

### 段階的実装の提案

**Phase 1**: セッション環境変数（既に必要性確認済み）
```yaml
defaults:
  session:
    env:
      EDITOR: "vim"
```

**Phase 2**: #161の要件を追加
```yaml
defaults:
  workspace:
    worktree_name_pattern: "{workspace_name}"
  session:
    env:
      EDITOR: "vim"
```

**Phase 3以降**: 実際の使用から必要になった設定を追加

### 実装の優先順位

1. セッション環境変数（本issue）- #159マージ後すぐ
2. worktreeディレクトリ名（#161）- 実用上の問題として次に対応
3. その他の設定 - 実際のニーズが出てから

この`defaults`名前空間を使った構造により、将来的な拡張も自然に行えます。具体的なニーズに基づいて段階的に機能を追加していくことで、過度な設計を避けつつ、実用的な設定システムを構築できると考えます。
