### ISSUE TITLE
Restrict arbitrary command execution to specific agents

### ISSUE THREAD

**Issue by choplin** [choplin/amux#171]
## Problem

Currently, `session_run` accepts any arbitrary string as `agent_id` and falls back to using it as a command name when the agent is not found in configuration. This creates potential security risks and makes it easy to accidentally execute wrong commands due to typos.

## Current Behavior

When using `session_run` with a non-existent agent_id:
1. The system doesn't validate if the agent exists
2. It silently falls back to using the agent_id as the command
3. Example: `agent_id: "nonexistent"` → tries to run command `nonexistent`

## Proposed Solution

1. **Validate agent_id**: Require that agent_id exists in configuration
2. **Explicit arbitrary commands**: Only allow arbitrary command execution through specific agents designed for it (e.g., `tmux` or `shell`)

### Example Configuration

```yaml
agents:
  tmux:
    type: tmux
    command: ""  # Empty = accepts arbitrary command
    description: "Run arbitrary commands in tmux session"
  
  test:
    type: process
    command: "go test ./..."
    description: "Run tests"
```

### Implementation Points

- Add validation in `session_tools.go` to check if agent exists
- Return clear error message when agent not found
- Only allow command override for agents that explicitly support it
- Suggest using 'tmux' agent for arbitrary commands in error messages

## Benefits

- **Security**: Prevents accidental execution of unintended commands
- **Clear intent**: Using specific agents like 'tmux' makes arbitrary command execution explicit
- **Type safety**: Configured agents can't be accidentally overridden
- **Better error messages**: Users get clear feedback about invalid agent_ids
