### ISSUE TITLE
Improve session_run tool description to prevent overuse for trivial commands

### ISSUE THREAD

**Issue by choplin** [choplin/amux#172]
## Problem

The current `session_run` tool description is causing AI agents to overuse it for trivial terminal commands like `ls`, `git status`, `touch`, etc. This creates unnecessary session overhead for simple operations that should use Claude's built-in tools.

## Current Issue

The phrase "Instead of trying to use bash directly" in the description misleads agents to use `session_run` for everything, even one-off commands that complete immediately.

## Proposed Solution

Update the tool description to clearly distinguish when to use `session_run` vs other tools:

```yaml
description: |
  Run an AI agent session for LONG-RUNNING or INTERACTIVE processes. 
  Creates and manages persistent sessions with proper lifecycle control.

  WHEN TO USE THIS TOOL:
  - Long-running processes (dev servers, watchers, builds)
  - Interactive programs requiring input (REPL, debuggers)
  - Test suites that take >30 seconds
  - Background tasks that need monitoring
  
  DO NOT USE FOR:
  - One-off commands that complete immediately (git, make, npm install, etc.)
  - Simple file operations (creating, reading, listing files)
  - Any command that exits after completion
  
  EXAMPLES OF GOOD USE:
  - session_run(agent_id: "test", command: "npm run dev")
  - session_run(agent_id: "python", command: "python -m pytest --watch")
  
  EXAMPLES OF BAD USE:
  - session_run(..., command: "git status") ❌ Use Bash tool
  - session_run(..., command: "ls") ❌ Use LS tool
  - session_run(..., command: "npm install") ❌ Use Bash tool
```

## Related Issues

This complements #171 (Restrict arbitrary command execution) by providing clearer guidance on appropriate tool usage. Once #171 is implemented, the description should also reflect that arbitrary commands require specific agents like 'tmux' or 'shell'.

## Benefits

- Reduces unnecessary session creation overhead
- Improves AI agent behavior and efficiency
- Clearer separation of concerns between tools
- Better resource utilization
