### ISSUE TITLE
Rename 'agent' to 'profile' in configuration

### ISSUE THREAD

**Issue by choplin** [choplin/amux#198]
## Problem

The current naming of "agent" in the configuration is misleading now that we support general command execution, not just AI agents. The "agent" acts as a template for launching sessions (similar to Docker image vs container relationship).

## Current State

```yaml
agents:
  dev-server:
    name: "Development Server"
    type: blocking
    params:
      command: "npm"
      args: ["run", "dev"]
```

## Proposed Change

Rename to "profile" or "session_profile":

```yaml
profiles:  # or session_profiles
  dev-server:
    name: "Development Server"
    type: blocking
    params:
      command: "npm"
      args: ["run", "dev"]
```

## Why "profile"?

- More accurate description of the functionality
- Similar to other tools (AWS profiles, Docker Compose profiles)
- Not limited to AI agents
- Clear that it's a template/configuration

## Impact

- Rename `agents` section to `profiles` in config
- Update all code references from "agent" to "profile"
- Update CLI commands (if any reference agents)
- Update documentation

## Implementation Steps

1. Add support for both names temporarily
2. Migrate existing configs
3. Deprecate old name
4. Remove old name support

This should be done in a separate PR after the session types feature is complete.
