### ISSUE TITLE
Support multiple backends for interactive sessions

### ISSUE THREAD

**Issue by choplin** [choplin/amux#200]
## Problem

Currently, interactive sessions are tightly coupled to tmux as the only backend. However, there are many other possible backends that could provide interactive session functionality.

## Vision

Separate session **type** (behavior) from session **backend** (implementation):
- **Session Type**: Defines behavior (interactive, blocking, command)
- **Session Backend**: Defines how it's implemented (tmux, docker, ssh, etc.)

## Possible Interactive Session Backends

1. **tmux** (current implementation) - Local terminal multiplexer
2. **Docker Container** - Interactive shell inside containers
3. **SSH** - Remote server interactive connections  
4. **Kubernetes Pod** - Similar to `kubectl exec`
5. **Cloud Shells** - AWS SSM Session Manager, GCP Cloud Shell, etc.
6. **Screen** - Alternative to tmux
7. **Local PTY** - Direct pseudo-terminal without tmux

## Example Configuration

```yaml
profiles:
  # tmux backend (current)
  local-dev:
    type: interactive
    backend: tmux
    params:
      command: bash
      
  # Docker backend
  isolated-env:
    type: interactive
    backend: docker
    params:
      image: python:3.11
      command: python
      volumes:
        - ./src:/app
      
  # SSH backend
  remote-server:
    type: interactive  
    backend: ssh
    params:
      host: dev.example.com
      user: developer
      key: ~/.ssh/id_rsa
      
  # Kubernetes backend
  k8s-debug:
    type: interactive
    backend: kubernetes
    params:
      pod: my-app-xyz
      container: app
      namespace: default
```

## Architecture Implications

1. Need to define a common interface for interactive backends
2. Each backend implements the same operations (start, stop, attach, send input)
3. Similar to container runtime architecture (Docker, containerd, CRI-O)

## Benefits

- More flexibility for users
- Better isolation options (containers)
- Remote development support (SSH, cloud)
- Cloud-native workflows (Kubernetes)
- Reduced dependency on tmux

## Implementation Approach

1. Define `InteractiveBackend` interface
2. Refactor current tmux code to implement this interface
3. Add new backends incrementally
4. Keep backward compatibility

## Related Issues

- #198 - Rename 'agent' to 'profile'
- #199 - Rename TmuxSession to InteractiveSession
- #109, #191 - Session types implementation

This is a future enhancement after the current session types work is complete.
