### ISSUE TITLE
Bug: Agent name is executed as command in tmux session when running 'amux run'

### ISSUE THREAD

**Issue by choplin** [choplin/amux#203]
## Description

When running `amux run default` with a configured agent, the agent name "default" is typed and executed as a bash command in the tmux session, causing an error.

## Steps to Reproduce

1. Create a config file with the following content:
```yaml
version: "1.0"

# MCP (Model Context Protocol) configuration
mcp:
  transport:
    type: stdio

# Agent configurations
agents:
  # Default agent for general development
  default:
    name: Default Shell
    type: tmux
    params:
      command: bash
      shell: /bin/bash
      windowName: dev
      autoAttach: false
    env:
      EDITOR: vim
```

2. Run `./amux run default`
3. Observe that "default" is typed and executed in the bash shell within the tmux session

## Root Cause

The issue is in `internal/core/agent/manager.go` in the `GetDefaultCommand` method. When an agent is not found or when no command is specified in the agent configuration, the method returns the agent ID itself as the command to execute (lines 113 and 128).

This causes the tmux session to receive the agent name as a command and execute it via `tmux send-keys`.

## Expected Behavior

- If an agent is not found, the command should fail with a clear error message
- If an agent exists but has no command configured, it should either:
  - Use a sensible default (like the configured shell)
  - Fail with a clear error message indicating that no command is configured

## Affected Code

- `internal/core/agent/manager.go`: GetDefaultCommand method (lines 107-129)
- `internal/cli/commands/session/run.go`: runSession function
- `internal/core/session/tmux_session.go`: Start method
